yandex_smart_home:
  filter:
    include_entity_globs:
      # hallway
      - sensor.energy_meter_total_t1
      - sensor.energy_meter_total_t2
      - binary_sensor.main_door
      # childrensroom
      - climate.childrensroom_ntrv16
      - input_text.smart_button2
      - sensor.childrensroom_th2_temperature
      - media_player.televizor_v_detskoi_2
      - humidifier.childrenroom
      - climate.childrens_q_lamp_air_cooler
      - light.childrens_q_lamp_rgb_lamp
      # bedroom
      - climate.bedroom_ntrv16
      - sensor.bedroom_th2_temperature
      - media_player.televizor_v_spalne_2
      - humidifier.bedroom
      - light.bedroom_q_lamp_rgb_lamp
      - climate.bedroom_q_lamp_air_cooler
      - button.bedroom_q_lamp_garland_power
      - vacuum.viomi_se
      - input_text.smart_button1
      # livingroom
      - climate.livingroom_ntrv16
      - sensor.livingroom_th2_temperature
      - media_player.televizor_v_gostinoi_2
      - humidifier.livingroom
      - light.night_light_livingroom_rgb_lamp
      - sensor.xerox_b215_multifunction_printer
      - light.mini_smart_switch1
      # bathroom
      - switch.bathroom_gidrolock
      - sensor.bathroom_warp_hot_water_total
      - sensor.bathroom_warp_cold_water_total
      - sensor.bathroom_th2_temperature
      - sensor.bathroom_warp_hot_water_temperature
      - sensor.bathroom_warp_cold_water_temperature
      # toilet
      - sensor.toilet_th2_temperature
      - sensor.toilet_warp_hot_water_total
      - sensor.toilet_warp_cold_water_total
      - sensor.toilet_warp_hot_water_temperature
      - sensor.toilet_warp_cold_water_temperature
      # kitchen
      - climate.kitchen_ntrv16
      - sensor.kitchen_th2_temperature
      - media_player.televizor_na_kukhne_2
      - light.mini_smart_switch2
      # balcony
      - sensor.balcony_th2_temperature

  entity_config:
    # hallway
    sensor.energy_meter_total_t1:
      name: Энергия день
      room: Прихожая
      properties:
        - type: electricity_meter
          unit_of_measurement: kWh
          entity: sensor.energy_meter_total_t1
        - type: power
          entity: sensor.energy_meter_power
    sensor.energy_meter_total_t2:
      name: Энергия ночь
      room: Прихожая
      properties:
        - type: electricity_meter
          unit_of_measurement: kWh
          entity: sensor.energy_meter_total_t2
    binary_sensor.main_door:
      name: Входная дверь
      room: Прихожая
      properties:
        - type: open
          entity: binary_sensor.main_door
        - type: battery_level
          entity: sensor.main_door_battery
        - type: illumination
          entity: sensor.main_door_illuminance
    # childrensroom
    climate.childrensroom_ntrv16:
      name: Батарея
      room: Детская
    input_text.smart_button2:
      device_class: button
      name: Кнопка
      room: Детская
    climate.childrens_q_lamp_air_cooler:
      name: Кондиционер
      room: Детская
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.childrens_q_lamp_air_cooler
        data:
          hvac_mode: cool
    humidifier.childrenroom:
      name: Увлажнитель
      room: Детская
      properties:
        - type: water_level
          entity: sensor.humidifier_childrenroom_water_level
    sensor.childrensroom_th2_temperature:
      name: Детская
      room: Детская
      properties:
        - type: temperature
          entity: sensor.childrensroom_th2_temperature
        - type: humidity
          entity: sensor.childrensroom_th2_humidity
        - type: battery_level
          entity: sensor.childrensroom_th2_battery
    light.childrens_q_lamp_rgb_lamp:
      name: "Лампа"
      room: "Детская"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    media_player.televizor_v_detskoi_2:
      name: Телевизор
      room: Детская
    # bedroom
    climate.bedroom_ntrv16:
      name: Батарея
      room: Спальня
    input_text.smart_button1:
      device_class: button
      name: Кнопка
      room: Спальня
    vacuum.viomi_se:
      name: Пылесос
      room: Спальня
    climate.bedroom_q_lamp_air_cooler:
      name: Кондиционер
      room: Спальня
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.bedroom_q_lamp_air_cooler
        data:
          hvac_mode: cool
      device_class: button
    button.bedroom_q_lamp_garland_power:
      name: Гирлянда
      room: Спальня
      # custom_toggles:
      # backlight:
      #   turn_on:
      #     service: button.press
      #     entity_id: button.garland_effect
      #   turn_off:
      #     service: button.press
      #     entity_id: button.garland_effect
    humidifier.bedroom:
      name: Увлажнитель
      room: Спальня
      properties:
        - type: water_level
          entity: sensor.humidifier_bedroom_water_level
    sensor.bedroom_th2_temperature:
      name: Спальня
      room: Спальня
      properties:
        - type: temperature
          entity: sensor.bedroom_th2_temperature
        - type: humidity
          entity: sensor.bedroom_th2_humidity
        - type: battery_level
          entity: sensor.bedroom_th2_battery
    light.bedroom_q_lamp_rgb_lamp:
      name: "Лампа"
      room: "Спальня"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    media_player.televizor_v_spalne_2:
      name: Телевизор
      room: Спальня
    # livingroom
    climate.livingroom_ntrv16:
      name: Батарея
      room: Гостиная
    humidifier.livingroom:
      name: Увлажнитель
      room: Гостиная
    sensor.xerox_b215_multifunction_printer:
      name: Принтер
      room: Гостиная
    sensor.livingroom_th2_temperature:
      name: Гостиная
      room: Гостиная
      properties:
        - type: temperature
          entity: sensor.livingroom_th2_temperature
        - type: humidity
          entity: sensor.livingroom_th2_humidity
        - type: battery_level
          entity: sensor.livingroom_th2_battery
    light.rgb_clock:
      name: "Часы"
      room: "Гостиная"
    light.mini_smart_switch1:
      name: "Гирлянда"
      room: "Гостиная"
    light.mini_smart_switch2:
      name: "Гирлянда"
      room: "Кухня"
    light.night_light_livingroom_rgb_lamp:
      name: "Лампа"
      room: "Гостиная"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    media_player.televizor_v_gostinoi_2:
      name: Телевизор
      room: Гостиная
    # bathroom
    sensor.bathroom_th2_temperature:
      name: Ванная
      room: Ванная
      properties:
        - type: temperature
          entity: sensor.bathroom_th2_temperature
        - type: humidity
          entity: sensor.bathroom_th2_humidity
        - type: battery_level
          entity: sensor.bathroom_th2_battery
    switch.bathroom_gidrolock:
      name: Вода
      room: Ванная
    sensor.bathroom_warp_hot_water_total:
      name: Счетчик горячей воды
      room: Ванная
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.bathroom_warp_hot_water_total
        - type: temperature
          entity: sensor.bathroom_warp_hot_water_temperature
    sensor.bathroom_warp_hot_water_temperature:
      name: Горячая вода
      room: Ванная
      properties:
        - type: temperature
          entity: sensor.bathroom_warp_hot_water_temperature
    sensor.bathroom_warp_cold_water_total:
      name: Счетчик холодной воды
      room: Ванная
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.bathroom_warp_cold_water_total
        - type: temperature
          entity: sensor.bathroom_warp_cold_water_temperature
    sensor.bathroom_warp_cold_water_temperature:
      name: Холодная вода
      room: Ванная
      properties:
        - type: temperature
          entity: sensor.bathroom_warp_cold_water_temperature
    # toilet
    sensor.toilet_th2_temperature:
      name: Туалет
      room: Туалет
      properties:
        - type: temperature
          entity: sensor.toilet_th2_temperature
        - type: humidity
          entity: sensor.toilet_th2_humidity
        - type: battery_level
          entity: sensor.toilet_th2_battery
    sensor.toilet_warp_hot_water_total:
      name: Счетчик горячей воды
      room: Туалет
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.toilet_warp_hot_water_total
        - type: temperature
          entity: sensor.toilet_warp_hot_water_temperature
    sensor.toilet_warp_hot_water_temperature:
      name: Горячая вода
      room: Туалет
      properties:
        - type: temperature
          entity: sensor.toilet_warp_hot_water_temperature
    sensor.toilet_warp_cold_water_total:
      name: Счетчик холодной воды
      room: Туалет
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.toilet_warp_cold_water_total
        - type: temperature
          entity: sensor.toilet_warp_cold_water_temperature
    sensor.toilet_warp_cold_water_temperature:
      name: Холодная вода
      room: Туалет
      properties:
        - type: temperature
          entity: sensor.toilet_warp_cold_water_temperature
    # kitchen
    climate.kitchen_ntrv16:
      name: Батарея
      room: Кухня
    sensor.kitchen_th2_temperature:
      name: Кухня
      room: Кухня
      properties:
        - type: temperature
          entity: sensor.kitchen_th2_temperature
        - type: humidity
          entity: sensor.kitchen_th2_humidity
        - type: battery_level
          entity: sensor.kitchen_th2_battery
    media_player.televizor_na_kukhne_2:
      name: Телевизор
      room: Кухня
    # balcony
    sensor.balcony_th2_temperature:
      name: Балкон
      room: Балкон
      properties:
        - type: temperature
          entity: sensor.balcony_th2_temperature
        - type: humidity
          entity: sensor.balcony_th2_humidity
        - type: battery_level
          entity: sensor.balcony_th2_battery
