yandex_smart_home:
  filter:
    include_entity_globs:
      - sensor.livingroom_th2_temperature
      - sensor.bedroom_th2_temperature
      - sensor.childrensroom_th2_temperature
      - sensor.kitchen_th2_temperature
      - sensor.balcony_th2_temperature
      - sensor.bathroom_th2_temperature
      - sensor.toilet_th2_temperature
      - switch.vannaia_switch
      - sensor.water_bathroom_hot_water_total
      - sensor.water_bathroom_cold_water_total
      - sensor.water_toilet_hot_water_total
      - sensor.water_toilet_cold_water_total
      - sensor.energy_meter_total_t1
      - sensor.energy_meter_total_t2
      - binary_sensor.main_door
      - sensor.0x00158d000246651d_action
      - light.rgb_clock
      # - light.hallway_light
      - media_player.televizor_v_gostinoi_2
      - media_player.televizor_v_detskoi_2
      - media_player.televizor_v_spalne_2
      - media_player.televizor_na_kukhne_2
      - sensor.mh_z19_co2_value
      - sensor.mh_z19_co2_value_2
      - sensor.co2
      - humidifier.uvlazhnitel
      # - humidifier.uvlazhnitel_2
      - humidifier.smartmi_evaporative_humidifier
      - light.night_light_livingroom_rgb_lamp
      - light.night_light_bedroom_rgb_lamp
      - light.night_light_childrens_rgb_lamp
      # - button.garland_power_2
      - switch.garland_on_off
      - climate.ir_remote_air_cooler
      - climate.air_cooler
  # color_profile:
  #   profile_clock:
  #     red: ["255", "0", "0"]
  #     green: ["0", "255", "0"]
  #     blue: ["0", "0", "255"]
  entity_config:
    # button.garland_power:
    #   name: Елочка
    #   room: Гостиная
    #   custom_toggles:
    #     backlight:
    #       turn_on:
    #         service: button.press
    #         entity_id: button.garland_effect
    #       turn_off:
    #         service: button.press
    #         entity_id: button.garland_effect
    climate.ir_remote_air_cooler:
      name: Кондиционер
      room: Детская
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.ir_remote_air_cooler
        data:
          hvac_mode: cool
    climate.air_cooler:
      name: Кондиционер
      room: Спальня
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.air_cooler
        data:
          hvac_mode: cool
    switch.garland_on_off:
      name: Гирлянда
      room: Спальня
      custom_toggles:
        backlight:
          turn_on:
            service: button.press
            entity_id: button.garland_effect
          turn_off:
            service: button.press
            entity_id: button.garland_effect
    humidifier.uvlazhnitel:
      name: Увлажнитель
      room: Детская
      properties:
        - type: water_level
          entity: sensor.uvlazhnitel_water_level
    # humidifier.uvlazhnitel_2:
    #   name: Гостиная
    #   room: Детская
    humidifier.smartmi_evaporative_humidifier:
      name: Увлажнитель
      room: Спальня
      properties:
        - type: water_level
          entity: sensor.smartmi_evaporative_humidifier_water_level
    sensor.mh_z19_co2_value:
      name: Воздух
      room: Спальня
      properties:
        - type: co2_level
          entity: sensor.mh_z19_co2_value
        - type: pm2.5_density
          entity: sensor.concentration2_2_5mm
        - type: pm1_density
          entity: sensor.concentration1_1_0mm
        - type: pm10_density
          entity: sensor.concentration3_10mm
    sensor.mh_z19_co2_value_2:
      name: Воздух
      room: Гостиная
      properties:
        - type: co2_level
          entity: sensor.mh_z19_co2_value_2
        - type: pm2.5_density
          entity: sensor.concentration2_2_5mm_2
        - type: pm1_density
          entity: sensor.concentration1_1_0mm_2
        - type: pm10_density
          entity: sensor.concentration3_10mm_2
    sensor.co2:
      name: Воздух
      room: Детская
      properties:
        - type: co2_level
          entity: sensor.co2
        - type: pm2.5_density
          entity: sensor.pm1006k_2_5mm_m3
        - type: pm1_density
          entity: sensor.pm1006k_1_0mm_m3
        - type: pm10_density
          entity: sensor.pm1006k_10_0mm_m3
        - type: humidity
          entity: sensor.humidity
    sensor.livingroom_th2_temperature:
      name: Гостиная
      room: Гостиная
      properties:
        - type: temperature
          entity: sensor.livingroom_th2_temperature
        - type: humidity
          entity: sensor.livingroom_th2_humidity
        - type: battery_level
          entity: sensor.livingroom_th2_battery
    sensor.bedroom_th2_temperature:
      name: Спальня
      room: Спальня
      properties:
        - type: temperature
          entity: sensor.bedroom_th2_temperature
        - type: humidity
          entity: sensor.bedroom_th2_humidity
        - type: battery_level
          entity: sensor.bedroom_th2_battery
    sensor.childrensroom_th2_temperature:
      name: Детская
      room: Детская
      properties:
        - type: temperature
          entity: sensor.childrensroom_th2_temperature
        - type: humidity
          entity: sensor.childrensroom_th2_humidity
        - type: battery_level
          entity: sensor.childrensroom_th2_battery
    sensor.kitchen_th2_temperature:
      name: Кухня
      room: Кухня
      properties:
        - type: temperature
          entity: sensor.kitchen_th2_temperature
        - type: humidity
          entity: sensor.kitchen_th2_humidity
        - type: battery_level
          entity: sensor.kitchen_th2_battery
    sensor.balcony_th2_temperature:
      name: Балкон
      room: Балкон
      properties:
        - type: temperature
          entity: sensor.balcony_th2_temperature
        - type: humidity
          entity: sensor.balcony_th2_humidity
        - type: battery_level
          entity: sensor.balcony_th2_battery
    sensor.toilet_th2_temperature:
      name: Туалет
      room: Туалет
      properties:
        - type: temperature
          entity: sensor.toilet_th2_temperature
        - type: humidity
          entity: sensor.toilet_th2_humidity
        - type: battery_level
          entity: sensor.toilet_th2_humidity
    sensor.bathroom_th2_temperature:
      name: Ванная
      room: Ванная
      properties:
        - type: temperature
          entity: sensor.bathroom_th2_temperature
        - type: humidity
          entity: sensor.bathroom_th2_humidity
        - type: battery_level
          entity: sensor.bathroom_th2_humidity
    switch.vannaia_switch:
      name: Вода
      room: Ванная
    sensor.water_bathroom_hot_water_total:
      name: Счетчик горячей воды
      room: Ванная
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.water_bathroom_hot_water_total
        - type: temperature
          entity: sensor.water_bathroom_hot_water_temperature
    sensor.water_bathroom_cold_water_total:
      name: Счетчик холодной воды
      room: Ванная
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.water_bathroom_cold_water_total
        - type: temperature
          entity: sensor.water_bathroom_cold_water_temperature
    sensor.water_toilet_hot_water_total:
      name: Счетчик горячей воды
      room: Туалет
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.water_toilet_hot_water_total
        - type: temperature
          entity: sensor.water_toilet_hot_water_temperature
    sensor.water_toilet_cold_water_total:
      name: Счетчик холодной воды
      room: Туалет
      properties:
        - type: water_meter
          unit_of_measurement: m3
          entity: sensor.water_toilet_cold_water_total
        - type: temperature
          entity: sensor.water_toilet_cold_water_temperature
    sensor.energy_meter_total_t1:
      name: Энергия день
      room: Прихожая
      properties:
        - type: electricity_meter
          unit_of_measurement: kWh
          entity: sensor.energy_meter_total_t1
        - type: power
          entity: sensor.energy_meter_power
    sensor.energy_meter_total_t2:
      name: Энергия ночь
      room: Прихожая
      properties:
        - type: electricity_meter
          unit_of_measurement: kWh
          entity: sensor.energy_meter_total_t2
    binary_sensor.main_door:
      name: Входная дверь
      room: Прихожая
      properties:
        - type: open
          entity: binary_sensor.main_door
        - type: battery_level
          entity: sensor.main_door_battery
    # sensor.0x00158d000246651d_action:
    #   device_class: button
    #   name: Кнопка беспроводная
    #   room: Спальня
    #   properties:
    #     # - type: button
    #     #   entity: sensor.0x00158d000246651d_action
    #     - type: battery_level
    #       entity: sensor.0x00158d000246651d_battery
    # light.hallway_light:
    #   name: "Люстра"
    #   room: "Прихожая"
    light.rgb_clock:
      name: "Часы"
      room: "Гостиная"
    light.night_light_livingroom_rgb_lamp:
      name: "Лампа"
      room: "Гостиная"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    light.night_light_bedroom_rgb_lamp:
      name: "Лампа"
      room: "Спальня"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    light.night_light_childrens_rgb_lamp:
      name: "Лампа"
      room: "Детская"
      modes:
        scene:
          candle:
            - "Fire"
          siren:
            - "Color_wipe"
          fantasy:
            - "Rainbow"
          garland:
            - "Fireworks"
    media_player.televizor_v_gostinoi_2:
      name: Телевизор
      room: Гостиная
    media_player.televizor_v_detskoi_2:
      name: Телевизор
      room: Детская
    media_player.televizor_v_spalne_2:
      name: Телевизор
      room: Спальня
    media_player.televizor_na_kukhne_2:
      name: Телевизор
      room: Кухня
