# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages
# Example configuration.yaml entry
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.3
mobile_app: #home assistant mobile application enable
