esphome:
  name: thread
  friendly_name: Thread

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hc9juMSXs0WMzcB5INqN9UOWASbiqJho9HAOTFcE5Jg="

ota:
  - platform: esphome
    password: "f60e326f9f208bcc692fdd4e486a38ce"

network:
  enable_ipv6: true

openthread:
  tlv: 4a0300000b0e080000000000010000000300000f35060004001fffe0020878d5a19009eab1700708fdb08abfdc01dc5f0510522246b644aa4e9ad923e8ef521d9540030e68612d7468726561642d623138300102b1800410ac8042d8fdbcc673668b1534fc0492350c0402a0f7f8

# Output and light configuration for a single red LED
output:
  - platform: gpio
    pin: GPIO15
    id: red_led

light:
  - platform: binary
    name: "Red LED"
    output: red_led