esphome:
  name: ${node_name}
  friendly_name: ${node_name}
  area: ${area_name}  

api:
  encryption:
    key: ${api_key}
    
ota:
  - platform: esphome
    password: ${ota_password}

network:
  enable_ipv6: true