substitutions:
  node_name: water-meter-test
  area_name: "Прихожая"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: ${node_name}
  ap_password: !secret ESPHOME_AP_PSW
  api_key: 123456
  ota_password: 123456

packages:
  package: !include
    file: common/common.yaml