substitutions:
  node_name: bathroom-warp
  area_name: "Ванная"
  api_key: "VyFDfXmbwbPoCYDfs0YqugTv25r/Dc1AN7s/pVUM/Kw="
  ota_password: "fd2a080cbdf630c48331e3265017b65f6"

packages:
  common: !include
    file: common/common.yaml
  warp: !include
    file: common/warp.yaml
    vars:
      hot_water_total_initial: '17.084'
      cold_water_total_initial: '30.695'
      hot_water_ratio_initial: '0.01'
      cold_water_ratio_initial: '0.01'
      hot_water_sn: '240542274'
      cold_water_sn: '240552244'

openthread:
  tlv: !secret openthread_tlv