substitutions:
  node_name: night-light-childrens
  area_name: "Детская"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: ${node_name}
  ap_password: !secret ESPHOME_AP_PSW
  api_key: "DykzQ9ZJsjOkvHb3mLgGxLKeKyJjEryDCQ9xTcvyUSg="
  ota_password: "ccc9aa7c8adbbac72906afc1b26db670"

esp32:
  board: lolin_s2_pico
  framework:
    type: arduino

packages:
  common: !include
    file: common/common.yaml
  rgb-lamp: !include
    file: common/rgb_lamp.yaml
    vars:
      ws2812_pin: 'GPIO2'