substitutions:
  node_name: night-light-livingroom
  area_name: "Гостиная"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: ${node_name}
  ap_password: !secret ESPHOME_AP_PSW
  api_key: "o14aY5u2hjkYs745ov/SUmO9Y1sp6E9auPzxCGvbivs="
  ota_password: "5f8c02f6d5535bd9aadd6f5d339ebcb5"

esp8266:
  board: d1_mini_pro

packages:
  common: !include
    file: common/common.yaml
  rgb-lamp: !include
    file: common/rgb_lamp.yaml
    vars:
      ws2812_pin: 'GPIO2'