substitutions:
  node_name: toilet-warp
  area_name: "Туалет"
  api_key: "hc9juMSXs0WMzcB5INqN9UOWASbiqJho9HAOTFcE5Jg="
  ota_password: "f60e326f9f208bcc692fdd4e486a38ce"

packages:
  common: !include
    file: common/common.yaml
  warp: !include
    file: common/warp.yaml
    vars:
      hot_water_total_initial: '10.772'
      cold_water_total_initial: '38.719'
      hot_water_ratio_initial: '0.01'
      cold_water_ratio_initial: '0.01'
      hot_water_sn: '240541874'
      cold_water_sn: '240539076'

openthread:
  tlv: 4a0300000b0e080000000000010000000300000f35060004001fffe0020878d5a19009eab1700708fdb08abfdc01dc5f0510522246b644aa4e9ad923e8ef521d9540030e68612d7468726561642d623138300102b1800410ac8042d8fdbcc673668b1534fc0492350c0402a0f7f8