substitutions:
  node_name: water-toilet
  area_name: "Туалет"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: ${node_name}
  ap_password: !secret ESPHOME_AP_PSW
  api_key: "0yiOCnCwJga8Z5APZnUX8tDIyMApTgr41mApgwkqrVA="
  ota_password: "516740d4cdbeff8546a53bebd2294c52"
  
packages:
  common: !include
    file: common/common.yaml
  water-meter: !include
    file: common/water-meter.yaml
    vars:
      hot_water_total_initial: '2.84'
      cold_water_total_initial: '13.54'
      hot_water_ratio_initial: '0.01'
      cold_water_ratio_initial: '0.01'
      hot_water_sn: '240541874'
      cold_water_sn: '240539076'