substitutions:
  node_name: water-bathroom
  area_name: "Ванная"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: ${node_name}
  ap_password: !secret ESPHOME_AP_PSW
  api_key: "Ok4p/HY+xl5kK7/4NSnp/2gHVUSlqYKlORowFXGL05c="
  ota_password: "aaf281aa6b1b8ebea40c354dc03e68a7"
  
packages:
  common: !include
    file: common/common.yaml
  water-meter: !include
    file: common/water-meter.yaml
    vars:
      hot_water_total_initial: '3.752'
      cold_water_total_initial: '8.524'
      hot_water_ratio_initial: '0.01'
      cold_water_ratio_initial: '0.01'
      hot_water_sn: '240542274'
      cold_water_sn: '240552244'